
# Konfigurasi dasar
symbol: "BTCUSDT"
timeframe: "5m"           # 1m, 5m, 15m, 1h, dsb
quote_size_usdt: 1.5      # modal per perdagangan (USDT). Perhatikan min 1 USDT (umum di pasar USDT)
live_trading: false       # false = paper-trade
exec_strategy: "sma_crossover"  # strategi yang boleh eksekusi live (kalau live_trading=true)

enabled_strategies:
  - sma_crossover
  - rsi
  - macd
  - bbands_mean_revert
  - donchian_breakout

risk:
  max_open_positions: 1
  take_profit_pct: 0.004      # 0.4%
  stop_loss_pct: 0.005        # 0.5%
  min_notional_usdt: 1.0      # cek notional minimal (USDT market)
  slippage_pct: 0.001         # 0.1%

backtest:
  lookback_days: 7
  initial_capital_usdt: 100.0
