symbol: "BTCUSDT"     # pasangan koin, mulai dari ini dulu
timeframe: "5m"       # 5 menit
quote_size_usdt: 1.5  # kira2 $1.5 per trade (>= 1 USDT)
live_trading: false   # AWALNYA: false (paper-trade)
exec_strategy: "sma_crossover"  # strategi yang eksekusi order saat live=true

enabled_strategies:
  - sma_crossover
  - rsi
  - macd
  - bbands_mean_revert
  - donchian_breakout

risk:
  max_open_positions: 1
  take_profit_pct: 0.004   # 0.4%
  stop_loss_pct: 0.005     # 0.5%
  min_notional_usdt: 1.0
  slippage_pct: 0.001

backtest:
  lookback_days: 7
  initial_capital_usdt: 100.0
